# Tutorial 3a - SVD Problem Described in the Class
#### In this problem we will determine U, V and $\Sigma$ for a non-square matrix by first principles

In [1]:
import numpy as np
import pandas as pd
from scipy import linalg

In [2]:
A=np.array([[1,0,1],[-2,1,0]])
A

array([[ 1,  0,  1],
       [-2,  1,  0]])

In [3]:
Atrans = np.transpose(A)

In [4]:
V = np.matmul(Atrans,A)
V

array([[ 5, -2,  1],
       [-2,  1,  0],
       [ 1,  0,  1]])

In [7]:
V_eigen_vals, V_eigen_vecs = np.linalg.eig(V)

In [8]:
V_eigen_vals

array([ 6.0000000e+00, -4.4408921e-16,  1.0000000e+00])

These are supposed to be the eigenvalues $\sigma_i$. Note that $\lambda_i = \sigma_i^2$.
i.e. $\sigma_i = \sqrt{\lambda_i}$

In [27]:
singular_values = np.sqrt(np.abs(V_eigen_vals))
print(singular_values)

[2.44948974e+00 2.10734243e-08 1.00000000e+00]


In [28]:
V_eigen_vecs # The column of this matrix are supposed to be the eigenvectors of V

array([[ 0.91287093, -0.40824829,  0.        ],
       [-0.36514837, -0.81649658,  0.4472136 ],
       [ 0.18257419,  0.40824829,  0.89442719]])

In [29]:
U = np.matmul(A,Atrans)
U

array([[ 2, -2],
       [-2,  5]])

In [30]:
U_eigen_vals, U_eigen_vecs = np.linalg.eig(U)

In [31]:
U_eigen_vals # These are supposed to be the square of the singular values of U.

array([1., 6.])

Note that these eigenvalues are same as that of V.

In [32]:
U_eigen_vecs

array([[-0.89442719,  0.4472136 ],
       [-0.4472136 , -0.89442719]])

Note that in the above, I did not determine U using V. I simply detetmined $AA^T$ and performed eigendecomposition.

Now, let check if the library function gives the same eigenvalues and vectors as we have determined.

In [33]:
U, S, VT = linalg.svd(A)

In [34]:
U

array([[-0.4472136 ,  0.89442719],
       [ 0.89442719,  0.4472136 ]])

In [35]:
S

array([2.44948974, 1.        ])

Note that the above singular values that we got using eigen-decomposition of $U$ are same as that we got from eigen-decomposition of $V$.

### Now let us try to determine $u_i$ vectors using V vectors and singular values $\sigma_i$.
$$ Av_i = \sigma_i u_i $$
$$ u_i = \frac{Av_i}{\sigma_i}$$
$$ u_1 = \frac{Av_1}{\sigma_1} ; u_2 = \frac{Av_2}{\sigma_2} $$

In [49]:
u_1 = np.matmul(A,V_eigen_vecs[:,0])/S[0] # S[0] is the first singular value.
print(u_1)
u_2 = np.matmul(A,V_eigen_vecs[:,1])/S[1] # S[1] is the second singular value.
print(u_2)

[ 0.4472136  -0.89442719]
[0.00000000e+00 1.11022302e-16]
