# Tutorial 3 - Principal Component Analysis

In [2]:
import numpy as np
import pandas as pd
from scipy import linalg

In [3]:
#data = pd.read_csv('data.csv')
#data
#data.shape
#M = data.values # this will convert data into a numpy array

In [4]:
M=np.array([[1,2,3],
   [4,3,7],
   [7,6,6]])

# Method 1: Using first principles approach

In [5]:
#extract dimensions of matrix
m,n = M.shape
M.shape

(3, 3)

In [6]:
#mean of each dimension
mn=np.mean(M,axis=0) # this will determine mean of each column
mn

array([4.        , 3.66666667, 5.33333333])

In [7]:
#create a matix of m rows(equal to observations)
Q=np.tile(mn, (m, 1)) # this is storing mean in each corresponding column
Q

array([[4.        , 3.66666667, 5.33333333],
       [4.        , 3.66666667, 5.33333333],
       [4.        , 3.66666667, 5.33333333]])

In [8]:
#subtract mean of each dimension from respective colummn
M1 = M-Q # this will give a zero mean data
M1

array([[-3.        , -1.66666667, -2.33333333],
       [ 0.        , -0.66666667,  1.66666667],
       [ 3.        ,  2.33333333,  0.66666667]])

In [9]:
#calculate covariance matrix
covariance = (1 / (m-1)) * np.matmul(M1, M1.transpose())
covariance

array([[ 8.61111111, -1.38888889, -7.22222222],
       [-1.38888889,  1.61111111, -0.22222222],
       [-7.22222222, -0.22222222,  7.44444444]])

In [10]:
#extract eigen values & eigen vectors of covariance matrix
w,v = np.linalg.eig(covariance)

In [11]:
#The eigenvalues
print(w,w.shape)

[ 1.53290584e+01 -4.32561421e-16  2.33760824e+00] (3,)


In [12]:
#The eigenvectors or the Principal components
print(v,v.shape)

[[-0.73679906  0.57735027  0.35184345]
 [ 0.06369416  0.57735027 -0.81400843]
 [ 0.6731049   0.57735027  0.46216498]] (3, 3)


In [13]:
# now the data can be projected along the principal directions.
projected_data1 = np.matmul(v.transpose(),M1)
# we use transpose of v since in the 'transformation matrix'
# the directions of PCs should be row vectors. Remember the P maxtrix in lecture.
print(projected_data1,projected_data1.shape)

[[ 4.22971186e+00  2.75611375e+00  2.27409134e+00]
 [ 0.00000000e+00  2.22044605e-16  8.88178420e-16]
 [ 3.30964575e-01  1.03465148e+00 -1.86953878e+00]] (3, 3)


# Method 2: Using svd function

In [14]:
m,n = M.shape
M.shape

(3, 3)

In [15]:
mn=np.mean(M,axis=0)
mn

array([4.        , 3.66666667, 5.33333333])

In [16]:
M2 = M-np.tile(mn,(m,1))
M2

array([[-3.        , -1.66666667, -2.33333333],
       [ 0.        , -0.66666667,  1.66666667],
       [ 3.        ,  2.33333333,  0.66666667]])

In [17]:
Y= M2.transpose() / np.sqrt(n-1)
Y

array([[-2.12132034,  0.        ,  2.12132034],
       [-1.1785113 , -0.47140452,  1.64991582],
       [-1.64991582,  1.1785113 ,  0.47140452]])

In [18]:
U, S, VT = linalg.svd(Y)

In [19]:
print(VT,VT.shape)

[[ 0.73679906 -0.06369416 -0.6731049 ]
 [-0.35184345  0.81400843 -0.46216498]
 [ 0.57735027  0.57735027  0.57735027]] (3, 3)


In [20]:
U

array([[-0.7639027 , -0.15306667, -0.62691567],
       [-0.49776505, -0.47851243,  0.72336423],
       [-0.4107099 ,  0.8646366 ,  0.28934569]])

In [21]:
S

array([3.91523415e+00, 1.52892388e+00, 2.03362035e-16])

In [22]:
S = np.diag(S) # this is the matrix of singular values i.e. \sqrt(lambda)
S

array([[3.91523415e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 1.52892388e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 2.03362035e-16]])

In [23]:
V = np.multiply(S,S) # This will give lambda values
V

array([[1.53290584e+01, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 2.33760824e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 4.13561174e-32]])

In [24]:
proj_data = np.matmul(VT.transpose(),M2) # now the data can be projected along the principal directions.
print(proj_data, proj_data.shape)

[[-0.47834637  0.3537145  -1.92070338]
 [ 1.92313329  0.91063528  1.8902006 ]
 [ 3.7513655   2.77710211  1.18520331]] (3, 3)


# Try the above using standardizing your data

In [25]:
def standardize(X): # X is the input data
    mu=sum(X)/len(X)
    var=sum((X-mu)**2)/len(X)
    z=(X-mu)/(var**0.5)
    return z

# SVD example of un-symmetrix matrix

In [28]:
A=np.array([[1,0,1],[-2,1,0]])
A

array([[ 1,  0,  1],
       [-2,  1,  0]])

In [29]:
Atrans = np.transpose(A)

In [30]:
U = np.matmul(Atrans,A)
U

array([[ 5, -2,  1],
       [-2,  1,  0],
       [ 1,  0,  1]])

In [33]:
eigen_vals, eigen_vecs = np.linalg.eig(U)

In [35]:
eigen_vals
eigen_vecs

array([[ 0.91287093, -0.40824829,  0.        ],
       [-0.36514837, -0.81649658,  0.4472136 ],
       [ 0.18257419,  0.40824829,  0.89442719]])

In [36]:
U, S, VT = linalg.svd(A)

In [37]:
U

array([[-0.4472136 ,  0.89442719],
       [ 0.89442719,  0.4472136 ]])

In [38]:
S

array([2.44948974, 1.        ])

In [39]:
VT

array([[-9.12870929e-01,  3.65148372e-01, -1.82574186e-01],
       [-3.73536832e-16,  4.47213595e-01,  8.94427191e-01],
       [-4.08248290e-01, -8.16496581e-01,  4.08248290e-01]])

In [40]:
V=np.transpose(VT)

In [41]:
V

array([[-9.12870929e-01, -3.73536832e-16, -4.08248290e-01],
       [ 3.65148372e-01,  4.47213595e-01, -8.16496581e-01],
       [-1.82574186e-01,  8.94427191e-01,  4.08248290e-01]])