# Mean, Variance and Covariance with numpy
We will use numpy directly and will consolidate our fundamentals. Pay attendtion to theory and compare the inference of these numerical examples

In [1]:
import numpy as np
from numpy import array # note that this time we are exporting array and mean directly so we dont have to use np.array etc.
from numpy import mean
from numpy import var

Calculating "mean" using mumpy

In [2]:
v = array([1,2,3,4,5,6])
print(v)
result = mean(v)
print(result)

[1 2 3 4 5 6]
3.5


Calculating "mean" of each row or column using mumpy

In [3]:
M = array([[1,2,3,4,5,6],[1,2,3,4,5,6]])
print(M)
col_mean = mean(M, axis=0)
print(col_mean)
row_mean = mean(M, axis=1)
print(row_mean)

[[1 2 3 4 5 6]
 [1 2 3 4 5 6]]
[1. 2. 3. 4. 5. 6.]
[3.5 3.5]


Variance calculation using numpy

In [4]:
v = array([1,2,3,4,5,6])
print(v)
result = var(v,ddof=1)
print(result)

[1 2 3 4 5 6]
3.5


In [5]:
v = array([1,2,3,4,5,6,7,8,9,10]) # Variance = (1/N-ddof)XX^{T}
print(v)
print("Variance=",var(v,ddof=0)) # Variance = (1/N-ddof)XX^{T}, if ddof is 0, we are dividing by N.
print("SD=",np.sqrt(var(v,ddof=0)))

[ 1  2  3  4  5  6  7  8  9 10]
Variance= 8.25
SD= 2.8722813232690143


Variance calculation of rows and columns using numpy

In [6]:
M = array([[1,2,3,4,5,6],[1,2,3,4,5,6]])
print(M)
col_variance = var(M, ddof=1, axis=0)
print(col_variance)
row_variance = var(M, ddof=1, axis=1)
print(row_variance)

[[1 2 3 4 5 6]
 [1 2 3 4 5 6]]
[0. 0. 0. 0. 0. 0.]
[3.5 3.5]


Standard deviation from variance

In [7]:
s = np.sqrt(row_variance)
print(s)

[1.87082869 1.87082869]


Standard deviation of rows and columns using numpy

In [8]:
M = array([[1,2,3,4,5,6],[1,2,3,4,5,6]])
print(M)
col_std = np.std(M, ddof=1, axis=0)
print(col_std)
row_std = np.std(M, ddof=1, axis=1)
print(row_std)

[[1 2 3 4 5 6]
 [1 2 3 4 5 6]]
[0. 0. 0. 0. 0. 0.]
[1.87082869 1.87082869]


Covariance between two arrays using numpy

In [9]:
x = array([1,2,3,4,5,6,7,8,9])
print(x)
y = array([9,8,7,6,5,4,3,2,1])
print(y)
x_var = np.var(x)
print(x_var)
y_var = np.var(y)
print(y_var)
covariance = np.cov(x,y)[0,1]
print(covariance)

[1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1]
6.666666666666667
6.666666666666667
-7.5


Probability Distribution, Expected Value and Variance
In the tutorial we will use probability distribution from the data of three tosses of coins as described in the class. The data will be used to determine the expected values and variance using many methods.

Px is the probability distribution for flip of a coin for three tosses. This distribution shows the probability of getting 0 Head, 1 Head, 2 Head and 3 Head during total three tosses. Refer to lecture slides.

In [1]:
Px = [1/8,3/8,3/8,1/8]
X=[0,1,2,3]

In [2]:
print(Px)
print(X)

[0.125, 0.375, 0.375, 0.125]
[0, 1, 2, 3]


In [3]:
sum(Px)

1.0

What is expectation for event X or the mean value for X i.e. for flipping a coin and getting head during three tosses. Here X is the event or Random variable. X has 4 values. X = 0 head, X = 1 head, X = 2 head, X = 3 head.
$ \mathbb{E}_{x \sim P}[ X ] = \sum_x {P(x)x}  = \mu $.
$\mu$ is the mean of the values of X. Note that we essentially determining a weighted average of X. This is weighted by the probability values at various values of X as per the probability distribution function.

In [5]:
E = Px[0]*X[0]+Px[1]*X[1]+Px[2]*X[2]+Px[3]*X[3]
E

1.5

Note that the expected value of the expectation is not a value that can be found in the original Px data for any value of X.

In [6]:
E=0
for i in X:
    E = E + X[i]*Px[i]
E
mu = E # mu is mean of X
mu

1.5

Variance is given by:
$$Var (x) = \mathbb{E} \left[ (X - \mu )^2 \right]  = \sum_x (x - \mu )^2 P(x)$$

In [7]:
VarX = 0
for i in X:
    VarX = VarX + ((X[i]-mu)**2)*Px[i]
VarX

0.75

Another form of variance is given by:
$$ E(X^2) - [E(X)]^2 = E(X^2) - \mu^2 $$
Let us try this: $E(X^2) - \mu^2$

In [8]:
EX2 = 0
EX2=0
for i in X:
    EX2 = EX2 + (X[i]**2)*Px[i]
VarX = EX2 - mu**2
print(VarX)

0.75


$$\sigma = \sqrt{Var(X)}$$

In [9]:
import numpy as np
SD = np.sqrt(VarX)
SD

0.8660254037844386